-- ============================================================
-- 1. DDL: TABLE CREATION & CONSTRAINTS
-- ============================================================

CREATE TABLE "subscriptions" (
    "plan_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "plan_name" VARCHAR(50) NOT NULL,
    "monthly_price" DECIMAL(5, 2) NOT NULL CHECK ("monthly_price" >= 0),
    "max_screens" INT NOT NULL CHECK ("max_screens" > 0)
);

CREATE TABLE "users" (
    "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "plan_id" INT REFERENCES "subscriptions"("plan_id") ON DELETE SET NULL,
    "username" VARCHAR(50) NOT NULL,
    "email" VARCHAR(100) UNIQUE NOT NULL,
    "signup_date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "profiles" (
    "profile_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" INT REFERENCES "users"("user_id") ON DELETE CASCADE,
    "profile_name" VARCHAR(50) NOT NULL,
    "is_kids" BOOLEAN DEFAULT FALSE
);

CREATE TABLE "media" (
    "media_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" VARCHAR(150) NOT NULL,
    "type" VARCHAR(20) CHECK ("type" IN ('Movie', 'Series_Episode')),
    "release_year" INT CHECK ("release_year" >= 1900),
    "duration_minutes" INT NOT NULL
);

CREATE TABLE "watch_history" (
    "history_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "profile_id" INT REFERENCES "profiles"("profile_id") ON DELETE CASCADE,
    "media_id" INT REFERENCES "media"("media_id") ON DELETE CASCADE,
    "watch_date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "progress_seconds" INT DEFAULT 0 CHECK ("progress_seconds" >= 0)
);


-- ============================================================
-- 2. DML: SAMPLE DATA INSERTION
-- ============================================================

-- Subscriptions
INSERT INTO "subscriptions" ("plan_name", "monthly_price", "max_screens") VALUES ('Standard', 13.49, 2);
INSERT INTO "subscriptions" ("plan_name", "monthly_price", "max_screens") VALUES ('Premium 4K', 19.99, 4);

-- Users
INSERT INTO "users" ("plan_id", "username", "email") VALUES (1, 'Alex2026', 'alex@email.com');
INSERT INTO "users" ("plan_id", "username", "email") VALUES (2, 'Sarah_M', 'sarah.m@email.com');

-- Profiles
INSERT INTO "profiles" ("user_id", "profile_name", "is_kids") VALUES (1, 'Alex', FALSE);
INSERT INTO "profiles" ("user_id", "profile_name", "is_kids") VALUES (1, 'Kids', TRUE);
INSERT INTO "profiles" ("user_id", "profile_name", "is_kids") VALUES (2, 'Sarah', FALSE);

-- Media
INSERT INTO "media" ("title", "type", "release_year", "duration_minutes") VALUES ('Cyberpunk Chronicles S01E01', 'Series_Episode', 2025, 45);
INSERT INTO "media" ("title", "type", "release_year", "duration_minutes") VALUES ('Inception 2', 'Movie', 2026, 148);
INSERT INTO "media" ("title", "type", "release_year", "duration_minutes") VALUES ('Space Adventures', 'Movie', 2024, 95);

-- Watch History
INSERT INTO "watch_history" ("profile_id", "media_id", "progress_seconds") VALUES (1, 1, 2700);
INSERT INTO "watch_history" ("profile_id", "media_id", "progress_seconds") VALUES (1, 2, 1200);
INSERT INTO "watch_history" ("profile_id", "media_id", "progress_seconds") VALUES (3, 2, 8880);


-- ============================================================
-- 3. DEMONSTRATION SQL QUERIES
-- ============================================================

-- Query 1: Profiles count per user account (Single JOIN)
SELECT u."username", u."email", COUNT(p."profile_id") AS total_profiles 
FROM "users" u 
JOIN "profiles" p ON u."user_id" = p."user_id" 
GROUP BY u."username", u."email";

-- Query 2: Total view count per media title (Media Popularity)
SELECT m."title", m."type", COUNT(wh."history_id") AS total_views 
FROM "media" m 
JOIN "watch_history" wh ON m."media_id" = wh."media_id" 
GROUP BY m."title", m."type";

-- Query 3: Total media watched per master billing account (Double JOIN)
SELECT u."username", u."email", COUNT(wh."history_id") AS total_media_watched 
FROM "users" u 
JOIN "profiles" p ON u."user_id" = p."user_id" 
JOIN "watch_history" wh ON p."profile_id" = wh."profile_id" 
GROUP BY u."username", u."email";

-- Query 4: Format media title with release year (String Concatenation)
SELECT "title" || ' (' || "release_year" || ')' AS "Full Title" 
FROM "media";

-- Query 5: Keyword search in catalog (Pattern Matching)
SELECT title, type, release_year, duration_minutes  
FROM media  
WHERE title LIKE '%Cyberpunk%';
